import Link from "next/link";
import { Card, PageHeader } from "@/components/hub";
import { freshDB } from "@/lib/fresh";
import Rediscover from "./Rediscover";

export default async function Tools({ searchParams }: { searchParams: Promise<{ app?: string }> }) {
  const { app } = await searchParams;
  const d = await freshDB();
  const apps = [d.tools, ...Object.values(d.catalogs ?? {})].filter((x): x is NonNullable<typeof x> => !!x);
  const c = apps.find((x) => x.app === app) ?? d.tools;
  return (
    <div className="space-y-4">
      <PageHeader title="Domain MCP" subtitle="Generated by the asky harness from the app itself (OpenAPI + a safe UI crawl). These tools are the vocabulary of the process graph, the events in Capture, and what agents can call." actions={<Rediscover />} />
      {!c ? (
        <Card tone="warn" title="No catalog yet"><p className="text-sm">Run <code>pnpm harness</code> (with the dev server running) or click “Rediscover”.</p></Card>
      ) : (
        <>
          {apps.length > 1 && (
            <div className="flex gap-1 rounded-xl bg-stone-200/60 p-1 text-sm w-fit">
              {apps.map((a) => (
                <Link key={a.app} href={a === d.tools ? "/hub/tools" : `/hub/tools?app=${a.app}`} className={`rounded-lg px-3 py-1.5 ${a.app === c.app ? "bg-white font-medium shadow-sm" : "text-stone-600 hover:text-stone-900"}`}>
                  {a.app === "ledgerline-ap" ? "Ledgerline AP · mock" : `${a.app} · real app`} <span className="text-xs text-stone-400">{a.tools.length}</span>
                </Link>
              ))}
            </div>
          )}
          <div className="text-xs text-stone-500">{c.app} · {c.baseUrl} · generated {new Date(c.generatedAt).toLocaleString()} by {c.generator}</div>
          {c.alignment && (
            <Card title={`Aligned with the knowledge vocabulary — ${c.alignment.filter((a) => a.tools.length).length}/${c.alignment.length} domain steps found`}>
              <p className="mb-3 text-xs text-stone-500">Pages, guardrails and the process graph speak in the mock app&apos;s steps. The harness matched each step to the tools it discovered in {c.app}, so the same knowledge applies here — with no hand-written mapping.</p>
              <table className="w-full text-sm [&_td]:py-1.5 [&_td]:pr-4">
                <tbody>
                  {c.alignment.map((a) => (
                    <tr key={a.canonical} className="border-t border-stone-100 align-top">
                      <td className="w-6">{a.tools.length ? <span className="text-emerald-600">✔</span> : <span className="text-rose-600">✗</span>}</td>
                      <td className="whitespace-nowrap"><code className="text-xs font-semibold">{a.canonical}</code></td>
                      <td className="whitespace-nowrap">{a.tools.map((t) => <code key={t} className="mr-1 rounded bg-amber-50 px-1 text-xs text-amber-900">{t}</code>)}</td>
                      <td className="text-xs text-stone-500">{a.note}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Card>
          )}
          <div className="overflow-hidden rounded-2xl border border-stone-200/80 bg-white shadow-[0_1px_2px_rgba(28,27,24,0.04)]">
            <table className="w-full text-sm [&_td]:pr-4 [&_th]:py-2.5 [&_th]:pr-4">
              <thead className="bg-stone-50/80 text-left text-[11px] font-medium uppercase tracking-wider text-stone-500"><tr><th className="px-4 py-2">Tool</th><th>Effect</th><th>Endpoint</th><th>Params</th><th>Seen in UI as</th></tr></thead>
              <tbody>
                {c.tools.map((t) => (
                  <tr key={t.name} className="border-t border-stone-100 align-top">
                    <td className="px-4 py-2"><code className="font-semibold">{t.name}</code><div className="text-xs text-stone-600">{t.description}</div><details className="text-[11px] text-stone-400"><summary>evidence</summary>{t.evidence.map((e, k) => <div key={k}>{e}</div>)}</details></td>
                    <td><span className={`rounded px-1.5 py-0.5 text-[11px] font-medium ${t.effect === "irreversible" ? "bg-rose-600 text-white" : t.effect === "write" ? "bg-amber-100 text-amber-900" : "bg-stone-100 text-stone-600"}`}>{t.effect}</span></td>
                    <td className="font-mono text-[11px]">{t.method} {t.pathTemplate}</td>
                    <td className="text-xs">{t.params.map((p) => `${p.name}${p.required ? "" : "?"}`).join(", ")}</td>
                    <td className="text-xs text-stone-500">{t.uiLabels.join(" · ")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
      <div className="grid grid-cols-2 gap-4">
        <Card title="Use it from an agent (MCP)">
          <pre className="overflow-x-auto rounded bg-stone-900 p-3 text-xs text-stone-100">{`{
  "mcpServers": {
    "ledgerline-ap": {
      "command": "pnpm",
      "args": ["--dir", "${process.cwd()}", "mcp"],
      "env": { "ASKY_URL": "http://localhost:3210" }
    }
  }
}`}</pre>
          <p className="mt-2 text-xs text-stone-500">Exposes every app tool plus <code>check_guardrail</code>, <code>find_pages</code>, <code>get_page</code> and <code>get_process</code>. Writes are refused when a guardrail is violated.</p>
        </Card>
        <Card title="Agent-ready export">
          <p className="text-sm text-stone-600">The pages and guardrails as instructions an agent can load — it follows the same steps and stops where the expert would.</p>
          <div className="mt-3 flex gap-2 text-sm">
            <a href="/api/export/agent" target="_blank" className="rounded-md bg-stone-900 px-3 py-1.5 text-white">Skill (Markdown)</a>
            <a href="/api/export/agent?format=json" target="_blank" className="rounded-md border border-stone-300 px-3 py-1.5">JSON</a>
          </div>
        </Card>
      </div>
    </div>
  );
}
