import { Card } from "@/components/hub";
import { freshDB } from "@/lib/fresh";
import Rediscover from "./Rediscover";

export default async function Tools() {
  const d = await freshDB();
  const c = d.tools;
  return (
    <div className="space-y-4">
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Domain MCP</h1>
          <p className="text-sm text-stone-500">Generated by the asky harness from the app itself (OpenAPI + a safe UI crawl). These tools are the vocabulary of the process graph, the events in Capture, and what agents can call.</p>
        </div>
        <Rediscover />
      </div>
      {!c ? (
        <Card tone="warn" title="No catalog yet"><p className="text-sm">Run <code>pnpm harness</code> (with the dev server running) or click “Rediscover”.</p></Card>
      ) : (
        <>
          <div className="text-xs text-stone-500">{c.app} · {c.baseUrl} · generated {new Date(c.generatedAt).toLocaleString()} by {c.generator}</div>
          <div className="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">
            <table className="w-full text-sm">
              <thead className="bg-stone-50 text-left text-xs text-stone-500"><tr><th className="px-4 py-2">Tool</th><th>Effect</th><th>Endpoint</th><th>Params</th><th>Seen in UI as</th></tr></thead>
              <tbody>
                {c.tools.map((t) => (
                  <tr key={t.name} className="border-t border-stone-100 align-top">
                    <td className="px-4 py-2"><code className="font-semibold">{t.name}</code><div className="text-xs text-stone-600">{t.description}</div><details className="text-[11px] text-stone-400"><summary>evidence</summary>{t.evidence.map((e, k) => <div key={k}>{e}</div>)}</details></td>
                    <td><span className={`rounded px-1.5 py-0.5 text-[11px] font-medium ${t.effect === "irreversible" ? "bg-rose-600 text-white" : t.effect === "write" ? "bg-amber-100 text-amber-900" : "bg-stone-100 text-stone-600"}`}>{t.effect}</span></td>
                    <td className="font-mono text-[11px]">{t.method} {t.pathTemplate}</td>
                    <td className="text-xs">{t.params.map((p) => `${p.name}${p.required ? "" : "?"}`).join(", ")}</td>
                    <td className="text-xs text-stone-500">{t.uiLabels.join(" · ")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
      <div className="grid grid-cols-2 gap-4">
        <Card title="Use it from an agent (MCP)">
          <pre className="overflow-x-auto rounded bg-stone-900 p-3 text-xs text-stone-100">{`{
  "mcpServers": {
    "ledgerline-ap": {
      "command": "pnpm",
      "args": ["--dir", "${process.cwd()}", "mcp"],
      "env": { "ASKY_URL": "http://localhost:3210" }
    }
  }
}`}</pre>
          <p className="mt-2 text-xs text-stone-500">Exposes every app tool plus <code>check_guardrail</code>, <code>find_pages</code>, <code>get_page</code> and <code>get_process</code>. Writes are refused when a guardrail is violated.</p>
        </Card>
        <Card title="Agent-ready export">
          <p className="text-sm text-stone-600">The pages and guardrails as instructions an agent can load — it follows the same steps and stops where the expert would.</p>
          <div className="mt-3 flex gap-2 text-sm">
            <a href="/api/export/agent" target="_blank" className="rounded-md bg-stone-900 px-3 py-1.5 text-white">Skill (Markdown)</a>
            <a href="/api/export/agent?format=json" target="_blank" className="rounded-md border border-stone-300 px-3 py-1.5">JSON</a>
          </div>
        </Card>
      </div>
    </div>
  );
}
